### ISSUE TITLE
add to pull-stream.github.io modules?

### ISSUE THREAD

**Issue by ahdinosaur** [dignifiedquire/pull-length-prefixed#1]
hey @dignifiedquire, awesome module!

just wondering, would you like this added to <https://pull-stream.github.io>? the process to add a module is as easy as pull request-ing a change to [pull-stream-docs/modules.md](https://github.com/pull-stream/pull-stream-docs/blob/master/modules.md), keen to include any modules that want to be a part of the ecosystem.

**Comment by dignifiedquire** [comment]
Yea please, I can make a PR there later today :)
